import wget

ligas = [

"http://www.nvhae.com/starcraft/img/Charas/Bengalaas.png",
"http://www.nvhae.com/starcraft/img/Charas/Arbiter.png",
"http://www.nvhae.com/starcraft/img/Charas/Archon.png",
"http://www.nvhae.com/starcraft/img/Charas/BattleCruiser.png",
"http://www.nvhae.com/starcraft/img/Charas/SCV.png",
"http://www.nvhae.com/starcraft/img/Charas/Broodling.png",
"http://www.nvhae.com/starcraft/img/Charas/BuildingBurst.png",
"http://www.nvhae.com/starcraft/img/Charas/Burst.png",
"http://www.nvhae.com/starcraft/img/Charas/Carrier.png",
"http://www.nvhae.com/starcraft/img/Charas/Civilian.png",
"http://www.nvhae.com/starcraft/img/Charas/Corsair.png",
"http://www.nvhae.com/starcraft/img/Charas/DarkTemplar.png",
"http://www.nvhae.com/starcraft/img/Charas/DarkArchon.png",
"http://www.nvhae.com/starcraft/img/Charas/Defiler.png",
"http://www.nvhae.com/starcraft/img/Charas/Dragoon.png",
"http://www.nvhae.com/starcraft/img/Charas/Drone.png",
"http://www.nvhae.com/starcraft/img/Charas/Dropship.png",
"http://www.nvhae.com/starcraft/img/Charas/Firebat.png",
"http://www.nvhae.com/starcraft/img/Charas/Ghost.png",
"http://www.nvhae.com/starcraft/img/Charas/Goliath.png",
"http://www.nvhae.com/starcraft/img/Charas/Guardian.png",
"http://www.nvhae.com/starcraft/img/Charas/HeroCruiser.png",
"http://www.nvhae.com/starcraft/img/Charas/Hydralisk.png",
"http://www.nvhae.com/starcraft/img/Charas/InfestedTerran.png",
"http://www.nvhae.com/starcraft/img/Charas/Kakaru.png",
"http://www.nvhae.com/starcraft/img/Charas/Kerrigan.png",
"http://www.nvhae.com/starcraft/img/Charas/Larva.png",
"http://www.nvhae.com/starcraft/img/Charas/Lurker.png",
"http://www.nvhae.com/starcraft/img/Charas/Magic.png",
"http://www.nvhae.com/starcraft/img/Charas/Marine.png",
"http://www.nvhae.com/starcraft/img/Charas/Medic.png",
"http://www.nvhae.com/starcraft/img/Charas/Mud.png",
"http://www.nvhae.com/starcraft/img/Charas/Mutalisk.png",
"http://www.nvhae.com/starcraft/img/Charas/Observer.png",
"http://www.nvhae.com/starcraft/img/Charas/Overlord.png",
"http://www.nvhae.com/starcraft/img/Charas/Portrait.png",
"http://www.nvhae.com/starcraft/img/Charas/Probe.png",
"http://www.nvhae.com/starcraft/img/Charas/ProtossBuilding.png",
"http://www.nvhae.com/starcraft/img/Charas/Queen.png",
"http://www.nvhae.com/starcraft/img/Charas/Ragnasaur.png",
"http://www.nvhae.com/starcraft/img/Charas/Reaver.png",
"http://www.nvhae.com/starcraft/img/Charas/Rhynsdon.png",
"http://www.nvhae.com/starcraft/img/Charas/SCV.png",
"http://www.nvhae.com/starcraft/img/Charas/Sarah.png",
"http://www.nvhae.com/starcraft/img/Charas/Scantid.png",
"http://www.nvhae.com/starcraft/img/Charas/Scourge.png",
"http://www.nvhae.com/starcraft/img/Charas/Scout.png",
"http://www.nvhae.com/starcraft/img/Charas/Shuttle.png",
"http://www.nvhae.com/starcraft/img/Charas/Tank.png",
"http://www.nvhae.com/starcraft/img/Charas/Tassadar.png",
"http://www.nvhae.com/starcraft/img/Charas/Templar.png",
"http://www.nvhae.com/starcraft/img/Charas/TerranBuilding.png",
"http://www.nvhae.com/starcraft/img/Charas/Ultralisk.png",
"http://www.nvhae.com/starcraft/img/Charas/Ursadon.png",
"http://www.nvhae.com/starcraft/img/Charas/Valkyrie.png",
"http://www.nvhae.com/starcraft/img/Charas/Vessel.png",
"http://www.nvhae.com/starcraft/img/Charas/Vulture.png",
"http://www.nvhae.com/starcraft/img/Charas/Wraith.png",
"http://www.nvhae.com/starcraft/img/Charas/Zealot.png",
"http://www.nvhae.com/starcraft/img/Charas/ZergBuilding.png",
"http://www.nvhae.com/starcraft/img/Charas/Zergling.png"
]

for i in ligas:
	print ("descargando : " + i) 
	d = wget.download(i)

